#ifndef NALIVATOR_PINS_H
#define NALIVATOR_PINS_H

#include "soc/gpio_num.h"
#include "soc/touch_sensor_channel.h"


#define LED_PIN GPIO_NUM_32
#define KEY_1_PIN GPIO_NUM_35
#define KEY_2_PIN GPIO_NUM_34
#define KEY_3_PIN GPIO_NUM_39
#define KEY_4_PIN GPIO_NUM_36
#define TOUCH_NEXT_PIN TOUCH_PAD_GPIO15_CHANNEL
#define TOUCH_PREV_PIN TOUCH_PAD_GPIO14_CHANNEL
#define SERVO_PIN GPIO_NUM_2
#define OLED_SDA_PIN GPIO_NUM_21
#define OLED_SCL_PIN GPIO_NUM_22
#define PUMPS_MOSI_PIN GPIO_NUM_23
#define PUMPS_SCK_PIN GPIO_NUM_18
#define PUMPS_SS_PIN GPIO_NUM_5
#define PUMP_1_PIN GPIO_NUM_13
#define PUMP_2_PIN GPIO_NUM_27
#define PUMP_3_PIN GPIO_NUM_26
#define PUMP_4_PIN GPIO_NUM_25
#define PUMP_5_PIN GPIO_NUM_33
#define PUMP_6_PIN GPIO_NUM_12
#define PUMP_7_PIN GPIO_NUM_19
#define PUMP_8_PIN GPIO_NUM_17
#define PUMP_9_PIN GPIO_NUM_16
#define PUMP_10_PIN GPIO_NUM_4

#endif //NALIVATOR_PINS_H