#ifndef NALIVATOR_WIFI_SETTINGS_H
#define NALIVATOR_WIFI_SETTINGS_H

#define WIFI_AP_SSID "Nalivator-AP"
#define WIFI_AP_PASS "123456789"
#define WIFI_MAXIMUM_RETRY 3

#endif //NALIVATOR_WIFI_SETTINGS_H